### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dvmuccillo** [dvmuccillo/designare#7]
- [ ] #6 Assets
  - [x] Mover templates base
  - [x] Mover designare_tags
  - [x] AssetsManager
    - [x] Mover componentes para Bower
    - [x] Criar tag para registro de dependências Bower por template
    - [x] Carregar js/css de acordo com componentes registrados 
    - [ ] Suporte a outros gerenciador de pacotes
    - [ ] Suporte a códigos não empacotados (snippets)
  - [x] Refatorar elementos reutilizáveis para componentes (menu, editor wysiwyg)  
  - [ ] Implementar Namespaces
    - [ ] Metodologias
    - [ ] Projetos
    - [x] Accounts
    - [ ] ...   
- [ ] Accounts
  - [x] Mover login/logout para accounts
  - [x] Informações Pessoais e de Acesso (CRUD)
  - [ ] Convites
  - [ ] Relação de amizade (contatos)
  - [ ] Visualizar perfil de outros usuários
  - [ ] Grupos
  - [ ] Equipes
  - [ ] Organizações
    - [ ] Definir Modelo
    - [ ] ...
- [ ] Permissões
  - [ ] Definir modelo e permissões para metodologias e projetos
  - [ ] Atualizar modelos para conter proprietários
  - [ ] Adaptar visualização/execução de acordo com permissões do usuário
  - [ ] Permissões padrão para determinado objeto (projeto,metodologia)
  - [ ] Permissões sobre objeto para grupos de usuários (grupos,organizações,equipes)
  - [ ] ...
- [ ] ...
